crademaster/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView, TemplateView

from allauth.account.views import LoginView, LogoutView

from executes.views import ExecuteCreateAPIView
from transactions.views import WithdrawCreateAPIView
from users.views import UserDetailAPIView, IDFileUploadView


urlpatterns = [
    path('', RedirectView.as_view(url='dashboard', permanent=False)),
    path('auth/', include('authentication.urls')),
    path('api/user-details/', UserDetailAPIView.as_view(), name='user_details'),
    path('api/activate/', ExecuteCreateAPIView.as_view(), name='execute_create'),
    path('api/withdraw/', WithdrawCreateAPIView.as_view(), name='withdraw_create'),
    path('api/upload/', IDFileUploadView.as_view(), name='id_file_upload'),

    path('accounts/login/', LoginView.as_view(), name='account_login'),
    path('accounts/signup/', TemplateView.as_view(), name="account_signup"),
    path('accounts/logout/', LogoutView.as_view(), name="account_logout"),

    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
]

fees/urls.py
from django.urls import path
from .views import (
    FeeListView, FeeUpdateView, RoayltyFeeListView, RoyaltyFeeUpdateView
)

urlpatterns = [
    path('', FeeListView.as_view(), name='fee_list'),
    path('<int:pk>/edit/', FeeUpdateView.as_view(), name='fee_update'),
    path('royalty/', RoayltyFeeListView.as_view(), name='royalty_fee_list'),
    path('royalty/<int:pk>/edit/', RoyaltyFeeUpdateView.as_view(), name='royalty_fee_update'),
]

users/urls.py
from django.urls import path
from .views import UserListView, UserUpdateView

urlpatterns = [
    path('', UserListView.as_view(), name='user_list'),
    path('<int:pk>/edit/', UserUpdateView.as_view(), name='user_update'),
]

executes/models.py
import math
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.timezone import now
from django.utils.timezone import localtime, now

from fees.models import RoyaltyFee

User = get_user_model()


class Execute(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.FloatField()
    duration = models.IntegerField(default=0)
    agent_os = models.CharField(max_length=10, null=True, blank=True)  # OS
    http_user_agent = models.CharField(max_length=40, null=True, blank=True)  # HTTP_USER_AGENT
    http_referer = models.CharField(max_length=40, null=True, blank=True)  # HTTP_REFERER
    http_x_forwarded_for = models.CharField(max_length=100, null=True, blank=True) # HTTP_X_FORWARDED_FOR
    profit_percent = models.DecimalField(max_digits=10, decimal_places=2, default=0.2)
    created = models.DateTimeField(default=now)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f"Execute from {self.user.email} is ${self.amount}"
    
    def get_duration(self):
        current_time = localtime(now())
        created_time = localtime(self.created)
        if created_time.date() == current_time.date():
            time_difference = (current_time - created_time).total_seconds()
        else:
            end_of_day = created_time.replace(hour=23, minute=59, second=59)
            time_difference = (end_of_day - created_time).total_seconds()
        return min(time_difference, self.duration * 3600)

    def get_profit(self):
        duration = self.get_duration()
        profit = self.amount * duration / 3600 * float(self.profit_percent) / 100
        return math.ceil(profit - self.get_platform_fee_amount())

    def get_platform_fee(self):
        fee = RoyaltyFee.get_fee_for_balance(self.amount)
        return fee.fee_percentage

    def get_platform_fee_amount(self):
        duration = self.get_duration()
        profit = self.amount * duration / 3600 * float(self.profit_percent) / 100
        return math.ceil(profit * float(self.get_platform_fee()) / 100)

users/models.py
import math
import uuid

from datetime import datetime

from tronpy import Tron
from tronpy.providers import HTTPProvider
from tronpy.exceptions import AddressNotFound

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models import Sum, Q
from django.utils import timezone
from django.utils.timezone import localtime, now
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager

from fees.models import Fee, RoyaltyFee
from fees.serializers import FeeSerializer

# tron = Tron(provider=HTTPProvider(api_key="679bbd65-8f55-4427-86a2-e4a4250be584"))
tron = Tron(network='nile')

# USDT_CONTRACT_ADDRESS = "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"
USDT_CONTRACT_ADDRESS = "TXYZopYRdj2D9XRtbG411XZZ3kM5VkAeBf"

class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True)
    wallet = models.CharField(_("wallet address"), max_length=150, blank=True)
    key = models.CharField(_("private key"), max_length=500, blank=True)

    cm_wallet = models.CharField(_("cm wallet address"), max_length=150, blank=True)
    cm_private_key = models.CharField(_("cm private key"), max_length=500, blank=True)
    cm_public_key = models.CharField(_("cm public key"), max_length=500, blank=True)
    cm_hex_address = models.CharField(_("cm hex address"), max_length=150, blank=True)

    profit_percent = models.DecimalField(max_digits=10, decimal_places=2, default=0.2)

    referral_code = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    referred_by = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='referrals')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email
    
    @property
    def get_balance(self):
        return self.get_deposit_balance + self.get_royalty_balance + self.get_profits

    @property
    def get_profits(self):
        total_profits = 0
        executes = self.execute_set.all().order_by('created')
        for execute in executes:
            total_profits += execute.get_profit()
        return float(total_profits)

    @property
    def get_deposit_balance(self):
        total_deposit = self.transactions.filter(
            transaction_type='DEPOSIT',
            status='COMPLETED'
        ).aggregate(total_deposit_amount=Sum('amount'))

        total_amount = total_deposit['total_deposit_amount'] or 0
        balance = self.get_usdt_balance
        return float(total_amount) + float(balance) - float(self.get_withdrawal_balance)

    @property
    def get_royalty_balance(self):
        total_royalty = self.transactions.filter(
            transaction_type='ROYALTY',
        ).aggregate(total_roaylty_amount=Sum('amount'))

        return total_royalty['total_roaylty_amount'] or 0

    @property
    def get_withdrawal_balance(self):
        total_withdraw = self.transactions.filter(
            transaction_type='WITHDRAWAL',
            status='COMPLETED'
        ).aggregate(total_withdraw_amount=Sum('amount'))

        return total_withdraw['total_withdraw_amount'] or 0

    @property
    def get_tron_balance(self):
        try:
            # balance = tron.get_account_balance("THAnMs85N6mcNbKuUbAX826eymbmB7uQs2")
            balance = tron.get_account_balance(self.cm_wallet)
        except AddressNotFound:
            balance = 0
        return balance

    @property
    def get_usdt_balance(self):
        try:
            contract = tron.get_contract(USDT_CONTRACT_ADDRESS)
            # balance = contract.functions.balanceOf("THAnMs85N6mcNbKuUbAX826eymbmB7uQs2")
            balance = contract.functions.balanceOf(self.cm_wallet)
            balance_in_usdt = balance / (10 ** 6)
        except AddressNotFound:
            balance_in_usdt = 0
        return balance_in_usdt

    @property
    def availability(self):
        balance = self.get_deposit_balance
        try:
            fee = Fee.get_fee_for_balance(balance)
            if fee:
                serializer = FeeSerializer(fee)
                return serializer.data
            return FeeSerializer(None).data
        except Exception:
            return FeeSerializer(None).data

    def calculate_total_execute(self):
        total_duration = 0
        executes = self.execute_set.all().order_by('created')

        for execute in executes:
            total_duration += execute.get_duration()
        return math.ceil(total_duration)

    def calculate_elapsed(self):
        execute = self.execute_set.first()

        if not execute or execute.created.date() != datetime.today().date():
            return 0
        elapsed = (timezone.now() - execute.created).total_seconds()
        return min(elapsed, 3600 * self.availability.get("hours"))


class IDFile(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    front = models.FileField(upload_to='uploads/')
    back = models.FileField(upload_to='uploads/')
    created = models.DateTimeField(auto_now_add=True)

users/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView

from rest_framework import generics
from rest_framework.permissions import IsAuthenticated

from authentication.mixins import StaffRequiredMixin
from authentication.serializers import CustomUserSerializer

from .models import CustomUser, IDFile
from .serializers import UploadedFilesSerializer


class UserListView(StaffRequiredMixin, ListView):
    model = CustomUser
    template_name = 'users/list.html'
    context_object_name = 'users'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.exclude(is_staff=True)


class UserUpdateView(StaffRequiredMixin, UpdateView):
    model = CustomUser
    fields = ['profit_percent']
    template_name = 'users/update.html'
    context_object_name = 'user'
    success_url = reverse_lazy('user_list')

    def get_object(self):
        return CustomUser.objects.get(id=self.kwargs['pk'])


# API view

class UserDetailAPIView(generics.RetrieveAPIView):
    queryset = CustomUser.objects.all()
    serializer_class = CustomUserSerializer
    permission_classes = [IsAuthenticated]

    def get_object(self):
        return self.request.user
    

class IDFileUploadView(generics.CreateAPIView):
    serializer_class = UploadedFilesSerializer
    permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        user = self.request.user
        serializer.save(user=user)

templates/users/list.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load custom_filters %}

{% block title %}
    Crademaster users
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-header pb-0">
              <h6>Users</h6>
            </div>
            <div class="card-body px-0 pt-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Email</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">USDT</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">TRX</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Profit Percent</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Total Hours</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Wallet</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Referral Code</th>
                      <th class="text-secondary opacity-7"></th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Executes</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for user in users %}
                        <tr>
                          <td>
                              <a href="{% url 'user_update' user.id %}"><span class="text-info text-xs font-weight-bold">{{ user.email }}</span></a>
                          </td>
                          <td class="align-middle text-center text-sm">
                            <span class="text-secondary text-xs font-weight-bold">{{ user.get_usdt_balance }}</span>
                          </td>
                          <td class="align-middle text-center text-sm">
                            <span class="text-secondary text-xs font-weight-bold">{{ user.get_tron_balance }}</span>
                          </td>
                          <td class="align-middle text-center text-sm">
                            <span class="text-secondary text-xs font-weight-bold">{{ user.profit_percent }} %</span>
                          </td>
                          <td class="align-middle text-center text-sm">
                            <span class="text-secondary text-xs font-weight-bold">{{ user.calculate_total_execute|seconds_to_hms }}</span>
                          </td>
                          <td class="align-middle text-center text-sm">
                              <span class="text-secondary text-xs font-weight-bold">{{ user.cm_wallet }}</span>
                          </td>
                          <td class="align-middle text-center">
                              <span class="text-secondary text-xs font-weight-bold">{{ user.referral_code }}</span>
                          </td>
                          <td class="align-middle">
                            <a href="{% url 'user_update' user.id %}" class="text-info font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Edit User">
                            Edit
                            </a>
                          </td>
                          <td class="align-middle text-center">
                            <a href="{% url 'execute_list' user.id %}" class="text-danger font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Edit User">
                            Executes
                            </a>
                          </td>
                        </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

templates/users/update.html
{% extends "dashboard/base.html" %}
{% load static %}
{% load custom_filters %}

{% block title %}
    Crademaster user
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-header pb-0">
              <h6>User</h6>
            </div>
            <div class="card-body px-0 pt-0 pb-2">
              <div class="card-header">
                <div class="row">
                    <div class="col-xl-3 col-md-6 mb-xl-0 mb-4">
                        <h6>Front</h6>
                        <img src="{{ user.idfile_set.first.front }}" alt="{{ image.title }}">
                    </div>
                    <div class="col-xl-3 col-md-6 mb-xl-0 mb-4">
                        <h6>Back</h6>
                        <img src="{{ user.idfile_set.first.back }}" alt="{{ image.title }}">
                    </div>
                </div>
                <div class="form-label">
                    <span class="mb-2 text-xs">Email: <span class="text-dark font-weight-normal ms-sm-2">{{ user.email }}</span></span>
                </div>
                <div class="form-label">
                    <span class="mb-2 text-xs">User Wallet: <span class="text-dark font-weight-normal ms-sm-2">{{ user.wallet|default_if_none:"" }}</span></span>
                </div>
                <div class="form-label">
                    <span class="mb-2 text-xs">Crademaster Wallet: <span class="text-dark font-weight-normal ms-sm-2">{{ user.cm_wallet }}</span></span>
                </div>
                <div class="form-label">
                    <span class="mb-2 text-xs">Crademaster Hex Address: <span class="text-dark font-weight-normal ms-sm-2">{{ user.cm_hex_address }}</span></span>
                </div>
                <div class="form-label">
                    <span class="mb-2 text-xs">Referral Code: <span class="text-dark font-weight-normal ms-sm-2">{{ user.referral_code }}</span></span>
                </div>
                <div class="form-label">
                    <span class="mb-2 text-xs">Referred By: <span class="text-dark font-weight-normal ms-sm-2">{{ user.referred_by|default_if_none:"" }}</span></span>
                </div>
                <form method="post">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label for="{{ form.profit_percent.id_for_label }}" class="form-label">Profit Percentage</label>
                        {{ form.profit_percent|add_class:"form-control" }}
                    </div>
                    {% if form.errors %}
                        <div class="text-danger">
                        {% for field_name, error_list in form.errors.items %}
                            {% for error in error_list %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        {% endfor %}
                        </div>
                    {% endif %}

                <div class="form-label">
                    <span class="mb-2 text-xs">Platform Fee: <span class="text-dark font-weight-normal ms-sm-2">{{ user.availability.fee_percentage }}</span></span>
                </div>
                <div class="form-label">
                    <span class="mb-2 text-xs">Available Hours: <span class="text-dark font-weight-normal ms-sm-2">{{ user.availability.hours }}</span></span>
                </div>
                <div class="form-label">
                    <span class="mb-2 text-xs">Total Platform Execute: <span class="text-dark font-weight-normal ms-sm-2">{{ user.calculate_total_execute|seconds_to_hms }}</span></span>
                </div>
              
                  <!-- Submit Button -->
                  <button type="submit" class="btn bg-gradient-info w-100 mt-4 mb-0">Update</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}